---
language: ruby
timeouts:
  bundle: 600
rvm:
 - 1.8.7
 - 1.9.3
 - 2.0.0
env:
  global: REDMINE_DIR=./workspace/redmine
  matrix:
  - REDMINE=2.2.4
  - REDMINE=2.3.1
  - REDMINE=master
matrix:
  exclude:
  - rvm: 2.0.0
    env: REDMINE_VER=2.2.4
  - rvm: 1.8.7
    env: REDMINE_VER=2.3.1
gemfile: workspace/redmine/Gemfile
bundlerargs: --without development rmagick
before_install:
 - sudo apt-get install -qq slapd ldap-utils
 - ./script/ci clone_redmine --target $REDMINE_DIR
 - cp ./config/database.yml.travis $REDMINE_DIR/config/database.yml
 - ./script/ci install_plugin
before_script:
 - ./script/ci prepare_redmine
 - ./script/ci prepare_plugin
 - ./script/ci start_ldap
 - 'phantomjs --webdriver 4444 2>&- 1>&- &'
script:
 - ./script/ci test
 - ./script/ci test_uninstall