---
language: ruby
timeouts:
  bundle: 600
rvm:
 - 1.8.7
 - 1.9.3
 - 2.0.0
env:
 - REDMINE_VER=2.2.4
 - REDMINE_VER=2.3.1
 - REDMINE_VER=master
matrix:
  exclude:
  - rvm: 2.0.0
    env: REDMINE_VER=2.2.4
  - rvm: 1.8.7
    env: REDMINE_VER=2.3.1
install:
 - export WORKSPACE=`pwd`/workspace
 - export PATH_TO_REDMINE=$WORKSPACE/redmine
 - export PATH_TO_LDAPSYNC=`pwd`
 - sudo apt-get install -qq slapd ldap-utils
 - ./script/redmine_install.sh -r || exit 1
 - ./script/redmine_install.sh -i || exit 1
before_script:
 - export PATH_TO_LDAPSYNC=`pwd`
 - script/startldap.sh || exit 1
 - phantomjs --webdriver 4444 2>&- 1>&- &
script:
 - export WORKSPACE=`pwd`/workspace
 - export PATH_TO_REDMINE=$WORKSPACE/redmine
 - export PATH_TO_LDAPSYNC=`pwd`
 - mkdir $WORKSPACE
 - cp config/database.yml.travis $WORKSPACE/database.yml
 - ./script/redmine_install.sh -t || exit 1
 - ./script/redmine_install.sh -u || exit 1