---
language: ruby
rvm:
 - 1.8.7
 - 1.9.3
 - 2.0.0
env:
 - REDMINE_VER=2.2.4
 - REDMINE_VER=2.3.1
 - REDMINE_VER=master
matrix:
  exclude:
  - rvm: 2.0.0
    env: REDMINE_VER=2.2.4
install: echo skip bundle install
before_script:
 - sudo apt-get install -qq slapd ldap-utils
 - export PATH_TO_LDAPSYNC=`pwd`
 - bash -x ./script/travis/startldap.sh || exit 1
script:
 - export WORKSPACE=`pwd`/workspace
 - export PATH_TO_LDAPSYNC=`pwd`
 - export PATH_TO_REDMINE=$WORKSPACE/redmine
 - mkdir $WORKSPACE
 - bash -x ./script/travis/redmine_install.sh -r || exit 1
 - bash -x ./script/travis/redmine_install.sh -i || exit 1
 - bash -x ./script/travis/redmine_install.sh -t || exit 1
 - bash -x ./script/travis/redmine_install.sh -u || exit 1