---
language: ruby
sudo: false
cache: bundler
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
rvm:
 - 1.8.7
 - 1.9.3
 - 2.2
 - 2.3.1
env:
  global: REDMINE_DIR=./workspace/redmine
  matrix:
   - REDMINE=2.6-stable
   - REDMINE=3.2-stable
   - REDMINE=master
matrix:
  exclude:
   - rvm: 1.8.7
     env: REDMINE=3.2-stable
   - rvm: 1.8.7
     env: REDMINE=master
   - rvm: 2.3.1
     env: REDMINE=2.6-stable
   - rvm: 2.3.1
     env: REDMINE=3.2-stable
gemfile: workspace/redmine/Gemfile
bundler_args: "--gemfile workspace/redmine/Gemfile --path workspace/redmine/vendor/bundle --without development rmagick"
before_install:
 - ./script/ci.sh clone_redmine --target $REDMINE_DIR
 - cp ./config/database.yml.travis $REDMINE_DIR/config/database.yml
 - ./script/ci.sh install_plugin_gemfile
before_script:
 - mysql -e 'CREATE DATABASE redmine CHARACTER SET utf8;'
 - ./script/ci.sh prepare_redmine
 - ./script/ci.sh prepare_plugin
 - ./script/ci.sh start_ldap
 - 'phantomjs --webdriver 4444 2>&- 1>&- &'
script:
 - ./script/ci.sh run_tests
 - ./script/ci.sh test_uninstall
